---
version: '3'

services:
  tmaskpl-web:
    container_name: tmaskpl-web
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - tmaskpl-postgres

  tmaskpl-postgres:
    container_name: tmaskpl-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}